### ISSUE TITLE
Chef::Exceptions::GroupIDNotFound: directory[/home/tamac/cloudfoundry/.deployments/devbox] (deployment::default line 17)

### ISSUE THREAD

**Issue by hamakn** [hamakn/software-design-2012-04#4]
TitleのエラーでCloud Foundryのインストールに失敗する

```
[Mon, 14 May 2012 16:58:23 +0900] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out[Mon, 14 May 2012 16:58:23 +0900] DEBUG: Chef::Exceptions::GroupIDNotFound: directory[/home/tamac/cloudfoundry/.deployments/devbox] (deployment::default line 17) had an error: Chef::Exceptions::GroupIDNotFound: cannot determine group id for '1000', does the group exist on this system?
/usr/lib/ruby/vendor_ruby/chef/file_access_control/unix.rb:79:in `target_gid'
/usr/lib/ruby/vendor_ruby/chef/file_access_control/unix.rb:83:in `set_group'
/usr/lib/ruby/vendor_ruby/chef/file_access_control/unix.rb:31:in `set_all'
/usr/lib/ruby/vendor_ruby/chef/mixin/enforce_ownership_and_permissions.rb:33:in `enforce_ownership_and_permissions'
/usr/lib/ruby/vendor_ruby/chef/provider/directory.rb:51:in `action_create'/usr/lib/ruby/vendor_ruby/chef/resource.rb:454:in `send'
/usr/lib/ruby/vendor_ruby/chef/resource.rb:454:in `run_action'
/usr/lib/ruby/vendor_ruby/chef/runner.rb:49:in `run_action'
/usr/lib/ruby/vendor_ruby/chef/runner.rb:85:in `converge'
/usr/lib/ruby/vendor_ruby/chef/runner.rb:85:in `each'
/usr/lib/ruby/vendor_ruby/chef/runner.rb:85:in `converge'
/usr/lib/ruby/vendor_ruby/chef/resource_collection.rb:94:in `execute_each_resource'/usr/lib/ruby/vendor_ruby/chef/resource_collection/stepable_iterator.rb:116:in `call'
/usr/lib/ruby/vendor_ruby/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block' 
/usr/lib/ruby/vendor_ruby/chef/resource_collection/stepable_iterator.rb:85:in `step' 
/usr/lib/ruby/vendor_ruby/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/usr/lib/ruby/vendor_ruby/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/usr/lib/ruby/vendor_ruby/chef/resource_collection.rb:92:in `execute_each_resource'
/usr/lib/ruby/vendor_ruby/chef/runner.rb:80:in `converge' /usr/lib/ruby/vendor_ruby/chef/client.rb:330:in `converge' 
/usr/lib/ruby/vendor_ruby/chef/client.rb:163:in `run'
/usr/lib/ruby/vendor_ruby/chef/application/solo.rb:207:in `run_application' 
/usr/lib/ruby/vendor_ruby/chef/application/solo.rb:195:in `loop' 
/usr/lib/ruby/vendor_ruby/chef/application/solo.rb:195:in `run_application'
/usr/lib/ruby/vendor_ruby/chef/application.rb:70:in `run'
/usr/bin/chef-solo:24
```

**Comment by hamakn** [comment]
最新版のChef 0.10.10だと必ず失敗するようです。

一時的に、古いバージョンを使うように修正しました。
https://github.com/hamakn/vcap/commit/8316d71b3cc44702ab0d214960f2caa8fad207dc
